-- 1. Create the users table
DROP TABLE IF EXISTS users CASCADE;
create table if not exists users (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text unique,
  phone text,
  avatar_url text,
  response_time text default 'פחות משעה',
  location text,
  joined_at text default 'מאי 2023',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the products table
DROP TABLE IF EXISTS products CASCADE;
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  rating numeric default 4.5,
  reviews integer default 0,
  category text not null,
  location text not null,
  description text not null,
  image text not null,
  lender_id uuid references users(id) on delete set null,
  lender_name text not null,
  lender_response_time text not null,
  lender_joined text not null,
  lender_image text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create the reviews table
-- 4. Create the bookings table
DROP TABLE IF EXISTS bookings CASCADE;
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  user_id uuid references users(id) on delete cascade not null,
  days integer not null default 1,
  total_price numeric not null,
  status text default 'אושר',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable Row Level Security (RLS)
alter table users enable row level security;
alter table products enable row level security;
alter table reviews enable row level security;
alter table bookings enable row level security;

-- 6. Create Policies for users table
drop policy if exists "Allow public read access to users" on users;
create policy "Allow public read access to users" on users
  for select using (true);

drop policy if exists "Allow public insert access to users" on users;
create policy "Allow public insert access to users" on users
  for insert with check (true);

drop policy if exists "Allow public update access to users" on users;
create policy "Allow public update access to users" on users
  for update using (true);

-- Create Policies for products table
drop policy if exists "Allow public read access to products" on products;
create policy "Allow public read access to products" on products
  for select using (true);

drop policy if exists "Allow public insert access to products" on products;
create policy "Allow public insert access to products" on products
  for insert with check (true);

-- Create Policies for reviews table
drop policy if exists "Allow public read access to reviews" on reviews;
create policy "Allow public read access to reviews" on reviews
  for select using (true);

drop policy if exists "Allow public insert access to reviews" on reviews;
create policy "Allow public insert access to reviews" on reviews
  for insert with check (true);

-- Create Policies for bookings table
drop policy if exists "Allow public read access to bookings" on bookings;
create policy "Allow public read access to bookings" on bookings
  for select using (true);

drop policy if exists "Allow public insert access to bookings" on bookings;
create policy "Allow public insert access to bookings" on bookings
  for insert with check (true);

-- 7. Seed initial users (Lenders and simulated users)
-- insert into users (id, full_name, email, phone, avatar_url, response_time, location, joined_at)
-- values
-- (1, 'ישראל ישראלי', 'israel@example.com', '050-1111111', 'https://i.pravatar.cc/150?u=israel', 'פחות משעה', 'תל אביב', 'מאי 2023'),
-- (2, 'מיכל כהן', 'michal@example.com', '050-2222222', 'https://i.pravatar.cc/150?u=michal', 'שעתיים', 'גבעתיים', 'אוגוסט 2022'),
-- (3, 'יוסי לוי', 'yossi@example.com', '050-3333333', 'https://i.pravatar.cc/150?u=yossi', '30 דקות', 'רמת גן', 'ינואר 2024'),
-- (4, 'דנה אברהם', 'dana@example.com', '050-4444444', 'https://i.pravatar.cc/150?u=dana', 'שעה', 'הרצליה', 'מרץ 2023'),
-- (5, 'רוני גבאי', 'roni@example.com', '050-5555555', 'https://i.pravatar.cc/150?u=roni', '4 שעות', 'חולון', 'יוני 2021'),
-- (6, 'עומר שטרן', 'omer@example.com', '050-6666666', 'https://i.pravatar.cc/150?u=omer', 'שעתיים', 'ראשון לציון', 'דצמבר 2023'),
-- (7, 'ליאת פז', 'liat@example.com', '050-7777777', 'https://i.pravatar.cc/150?u=liat', 'פחות משעה', 'רעננה', 'פברואר 2022'),
-- (8, 'אביב משה', 'aviv@example.com', '050-8888888', 'https://i.pravatar.cc/150?u=aviv', '5 שעות', 'פתח תקווה', 'אוקטובר 2023'),
-- (9, 'עידן רייכל', 'idan@example.com', '050-9999999', 'https://i.pravatar.cc/150?u=idan', 'שעתיים', 'כפר סבא', 'ספטמבר 2022'),
-- (10, 'גדי וילצ''רסקי', 'gadi@example.com', '050-1010101', 'https://i.pravatar.cc/150?u=gadi', 'יום', 'חיפה', 'יולי 2023'),
-- (11, 'משתמש נוכחי', 'current@example.com', '054-0000000', 'https://i.pravatar.cc/150?u=currentUser', 'פחות משעה', 'תל אביב', 'מאי 2026')
-- on conflict (id) do nothing;

-- 8. Seed initial products (with lender_id referencing users)
insert into products (id, name, price, rating, reviews, category, location, description, image, lender_id, lender_name, lender_response_time, lender_joined, lender_image)
values
(
  1,
  'מקדחה מקצועית מקיטה',
  40,
  4.8,
  12,
  'כלי עבודה',
  '200 מ'' ממך',
  'מקדחה חזקה ואמינה, מתאימה לכל עבודות הבית. כולל סט מקדחים בסיסי. קלה לתפעול ונוחה לאחיזה.',
  'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800',
  NULL,
  'ישראל ישראלי',
  'פחות משעה',
  'מאי 2023',
  'https://i.pravatar.cc/150?u=israel'
),
(
  2,
  'אוהל 4 אנשים - פתיחה מהירה',
  60,
  4.9,
  8,
  'מחנאות',
  '500 מ'' ממך',
  'אוהל בן-רגע ל-4 אנשים, מושלם לקמפינג משפחתי. הקמה תוך 60 שניות. עמיד בגשם ורוח.',
  'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800',
  NULL,
  'מיכל כהן',
  'שעתיים',
  'אוגוסט 2022',
  'https://i.pravatar.cc/150?u=michal'
),
(
  3,
  'מיקסר קיטשן אייד - אדום',
  55,
  4.7,
  15,
  'מטבח',
  '1.2 ק"מ ממך',
  'המיקסר הקלאסי והחזק של KitchenAid. מגיע עם וו לישה, מקצף ואביזר גיטרה. אידיאלי לאפייה מקצועית.',
  'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800',
  NULL,
  'יוסי לוי',
  '30 דקות',
  'ינואר 2024',
  'https://i.pravatar.cc/150?u=yossi'
),
(
  4,
  'מקרן קולנוע ביתי 4K',
  80,
  5.0,
  5,
  'אירוח',
  '800 מ'' ממך',
  'מקרן 4K איכותי לחוויית קולנוע ביתית מושלמת. הבהירות גבוהה וחיבור פשוט לכל מכשיר. כולל מסך הקרנה מתקפל.',
  'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&q=80&w=800',
  NULL,
  'דנה אברהם',
  'שעה',
  'מרץ 2023',
  'https://i.pravatar.cc/150?u=dana'
),
(
  5,
  'סט כלי עבודה חשמליים',
  120,
  4.6,
  20,
  'כלי עבודה',
  '1.5 ק"מ ממך',
  'סט מקיף הכולל מברגה, משחזת זווית ומסור אנכי. הכל מופעל על סוללות נטענות (כלולות).',
  'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=800',
  NULL,
  'רוני גבאי',
  '4 שעות',
  'יוני 2021',
  'https://i.pravatar.cc/150?u=roni'
),
(
  6,
  'שק שינה לטמפרטורות קיצון',
  30,
  4.5,
  3,
  'מחנאות',
  '2.1 ק"מ ממך',
  'שק שינה איכותי המתאים לטמפרטורות של עד -5 מעלות. קל משקל ונוח לנשיאה.',
  'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?auto=format&fit=crop&q=80&w=800',
  NULL,
  'עומר שטרן',
  'שעתיים',
  'דצמבר 2023',
  'https://i.pravatar.cc/150?u=omer'
),
(
  7,
  'מכונת קפה אספרסו',
  45,
  4.9,
  25,
  'מטבח',
  '900 מ'' ממך',
  'מכונת אספרסו ביתית המפיקה קפה באיכות בית קפה. כולל מקציף חלב מובנה.',
  'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800',
  NULL,
  'ליאת פז',
  'פחות משעה',
  'פברואר 2022',
  'https://i.pravatar.cc/150?u=liat'
),
(
  8,
  'כיסאות מתקפלים לאירוח',
  15,
  4.3,
  30,
  'אירוח',
  '400 מ'' ממך',
  'סט של 10 כיסאות מתקפלים חזקים ונוחים. מושלם לאירועים בחצר או בבית.',
  'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&q=80&w=800',
  NULL,
  'אביב משה',
  '5 שעות',
  'אוקטובר 2023',
  'https://i.pravatar.cc/150?u=aviv'
),
(
  9,
  'אופני הרים מקצועיות',
  70,
  4.7,
  7,
  'ספורט',
  '3.2 ק"מ ממך',
  '',
  NULL,
  'עידן רייכל',
  'שעתיים',
  'ספטמבר 2022',
  'https://i.pravatar.cc/150?u=idan'
),
(
  10,
  'מסור חשמלי לגינה',
  50,
  4.4,
  4,
  'גינה',
  '1.8 ק"מ ממך',
  '',
  NULL,
  'גדי וילצ''רסקי',
  'יום',
  'יולי 2023',
  'https://i.pravatar.cc/150?u=gadi'
)
on conflict (id) do nothing;
(
  1,
  'מקדחה מקצועית מקיטה',
  40,
  4.8,
  12,
  'כלי עבודה',
  '200 מ'' ממך',
  'מקדחה חזקה ואמינה, מתאימה לכל עבודות הבית. כולל סט מקדחים בסיסי. קלה לתפעול ונוחה לאחיזה.',
  'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800',
  'ישראל ישראלי',
  'פחות משעה',
  'מאי 2023',
  'https://i.pravatar.cc/150?u=israel'
),
values
(
  1, 
  'מקדחה מקצועית מקיטה', 
  40, 
  4.8, 
  12, 
  'כלי עבודה', 
  '200 מ'' ממך', 
  'מקדחה חזקה ואמינה, מתאימה לכל עבודות הבית. כולל סט מקדחים בסיסי. קלה לתפעול ונוחה לאחיזה.', 
  'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800', 
  1,
  'ישראל ישראלי', 
  'פחות משעה', 
  'מאי 2023', 
  'https://i.pravatar.cc/150?u=israel'
),
(
  2, 
  'אוהל 4 אנשים - פתיחה מהירה', 
  60, 
  4.9, 
  8, 
  'מחנאות', 
  '500 מ'' ממך', 
  'אוהל בן-רגע ל-4 אנשים, מושלם לקמפינג משפחתי. הקמה תוך 60 שניות. עמיד בגשם ורוח.', 
  'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800', 
  2,
  'מיכל כהן', 
  'שעתיים', 
  'אוגוסט 2022', 
  'https://i.pravatar.cc/150?u=michal'
),
(
  3, 
  'מיקסר קיטשן אייד - אדום', 
  55, 
  4.7, 
  15, 
  'מטבח', 
  '1.2 ק"מ ממך', 
  'המיקסר הקלאסי והחזק של KitchenAid. מגיע עם וו לישה, מקצף ואביזר גיטרה. אידיאלי לאפייה מקצועית.', 
  'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800', 
  3,
  'יוסי לוי', 
  '30 דקות', 
  'ינואר 2024', 
  'https://i.pravatar.cc/150?u=yossi'
),
(
  4, 
  'מקרן קולנוע ביתי 4K', 
  80, 
  5.0, 
  5, 
  'אירוח', 
  '800 מ'' ממך', 
  'מקרן 4K איכותי לחוויית קולנוע ביתית מושלמת. בהירות גבוהה וחיבור פשוט לכל מכשיר. כולל מסך הקרנה מתקפל.', 
  'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&q=80&w=800', 
  4,
  'דנה אברהם', 
  'שעה', 
  'מרץ 2023', 
  'https://i.pravatar.cc/150?u=dana'
),
(
  5, 
  'סט כלי עבודה חשמליים', 
  120, 
  4.6, 
  20, 
  'כלי עבודה', 
  '1.5 ק"מ ממך', 
  'סט מקיף הכולל מברגה, משחזת זווית ומסור אנכי. הכל מופעל על סוללות נטענות (כלולות).', 
  'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=800', 
  5,
  'רוני גבאי', 
  '4 שעות', 
  'יוני 2021', 
  'https://i.pravatar.cc/150?u=roni'
),
(
  6, 
  'שק שינה לטמפרטורות קיצון', 
  30, 
  4.5, 
  3, 
  'מחנאות', 
  '2.1 ק"מ ממך', 
  'שק שינה איכותי המתאים לטמפרטורות של עד -5 מעלות. קל משקל ונוח לנשיאה.', 
  'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?auto=format&fit=crop&q=80&w=800', 
  6,
  'עומר שטרן', 
  'שעתיים', 
  'דצמבר 2023', 
  'https://i.pravatar.cc/150?u=omer'
),
(
  7, 
  'מכונת קפה אספרסו', 
  45, 
  4.9, 
  25, 
  'מטבח', 
  '900 מ'' ממך', 
  'מכונת אספרסו ביתית המפיקה קפה באיכות בית קפה. כולל מקציף חלב מובנה.', 
  'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800', 
  7,
  'ליאת פז', 
  'פחות משעה', 
  'פברואר 2022', 
  'https://i.pravatar.cc/150?u=liat'
),
(
  8, 
  'כיסאות מתקפלים לאירוח', 
  15, 
  4.3, 
  30, 
  'אירוח', 
  '400 מ'' ממך', 
  'סט של 10 כיסאות מתקפלים חזקים ונוחים. מושלם לאירועים בחצר או בבית.', 
  'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&q=80&w=800', 
  8,
  'אביב משה', 
  '5 שעות', 
  'אוקטובר 2023', 
  'https://i.pravatar.cc/150?u=aviv'
),
(
  9, 
  'אופני הרים מקצועיות', 
  70, 
  4.7, 
  7, 
  'ספורט', 
  '3.2 ק"מ ממך', 
  9,
  'עידן רייכל', 
  'שעתיים', 
  'ספטמבר 2022', 
  'https://i.pravatar.cc/150?u=idan'
),
(
  10, 
  'מסור חשמלי לגינה', 
  50, 
  4.4, 
  4, 
  'גינה', 
  '1.8 ק"מ ממך', 
  10,
  'גדי וילצ''רסקי', 
  'יום', 
  'יולי 2023', 
  'https://i.pravatar.cc/150?u=gadi'
)
on conflict (id) do nothing;

-- 9. Seed initial reviews
insert into reviews (id, product_id, user_name, rating, date_text, comment)
values
(1, 1, 'רון לביא', 5, 'לפני שבועיים', 'מקדחה מצוינת, עשתה את העבודה בקלות. ישראל היה מאוד נחמד וגמיש בזמנים.'),
(2, 1, 'מיכל שרון', 4, 'לפני חודש', 'אחלה מכשיר, הגיע עם כל החלקים. היה קצת אבק אבל לא נורא.'),
(3, 2, 'דודו אהרון', 5, 'לפני 3 ימים', 'האוהל הכי נוח שהיה לי! נפתח באמת תוך דקה. נקי ומסודר.'),
(4, 2, 'יעל שלביה', 5, 'לפני שבועיים', 'שירות מעולה של מיכל. האוהל היה במצב חדש.'),
(5, 3, 'נועה קירל', 5, 'לפני שבוע', 'הכנתי איתו עוגות לכל המשפחה. עובד כמו סוס. יוסי מקסים!'),
(6, 4, 'סטטיק', 5, 'אתמול', 'וואו! איכות מטורפת. המקרן קטן וקומפקטי אבל התמונה ענקית וחדה.'),
(7, 4, 'בן אל', 5, 'לפני שבוע', 'סגר לנו פינה לערב סרט עם החבר''ה. דנה הייתה סופר נחמדה.'),
(8, 5, 'עומר אדם', 4, 'לפני חודש', 'סט מעולה לשיפוץ. הסוללות מחזיקות המון זמן.'),
(9, 6, 'עדן בן זקן', 5, 'לפני שבועיים', 'היה לי חם ונעים כל הלילה בחרמון. מומלץ!'),
(10, 7, 'מרגי', 5, 'לפני 5 ימים', 'קפה מושלם. המכונה נקייה ופשוטה לשימוש.'),
(11, 8, 'אנה זק', 4, 'לפני שבוע', 'כיסאות נוחים, עשו את העבודה במסיבת יום הולדת.'),
(12, 9, 'טדי נגוסה', 5, 'לפני שבועיים', 'אופניים מטורפים, נהניתי מכל רגע במסלול.'),
(13, 10, 'רביד פלוטניק', 5, 'לפני חודש', 'מסור חזק מאוד. גדי הסביר לי הכל בסבלנות.')
on conflict (id) do nothing;

-- 10. Reset primary key sequences (so new items added get correct next IDs)
select setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1)) from users;
select setval(pg_get_serial_sequence('products', 'id'), coalesce(max(id), 1)) from products;
select setval(pg_get_serial_sequence('reviews', 'id'), coalesce(max(id), 1)) from reviews;
select setval(pg_get_serial_sequence('bookings', 'id'), coalesce(max(id), 1)) from bookings;
