-- 1. Create the users table
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

create table users (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text unique,
  phone text,
  avatar_url text,
  response_time text default 'פחות משעה',
  location text,
  joined_at text default 'מאי 2023',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the products table (includes lender_phone + lender_email for seeded items)
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  rating numeric default 4.5,
  reviews integer default 0,
  category text not null,
  location text not null,
  description text not null default '',
  image text not null default '',
  lender_id uuid references users(id) on delete set null,
  lender_name text not null,
  lender_phone text default '',
  lender_email text default '',
  lender_response_time text not null,
  lender_joined text not null,
  lender_image text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create the reviews table
create table reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  user_name text not null,
  rating integer not null default 5,
  date_text text,
  comment text
);

-- 4. Create the bookings table
create table bookings (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  user_id uuid references users(id) on delete cascade not null,
  days integer not null default 1,
  total_price numeric not null,
  status text default 'אושר',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable Row Level Security (RLS)
alter table users enable row level security;
alter table products enable row level security;
alter table reviews enable row level security;
alter table bookings enable row level security;

-- 6. RLS Policies

-- users: כל אחד יכול לקרוא, רק המשתמש עצמו יכול לעדכן
drop policy if exists "Public read users" on users;
create policy "Public read users" on users for select using (true);

drop policy if exists "Insert own user row" on users;
create policy "Insert own user row" on users for insert with check (auth.uid() = id);

drop policy if exists "Update own user row" on users;
create policy "Update own user row" on users for update using (auth.uid() = id);

-- products: כל אחד קורא, מחובר יכול להוסיף
drop policy if exists "Public read products" on products;
create policy "Public read products" on products for select using (true);

drop policy if exists "Auth insert products" on products;
create policy "Auth insert products" on products for insert with check (auth.uid() is not null);

-- reviews: כל אחד קורא, מחובר יכול להוסיף
drop policy if exists "Public read reviews" on reviews;
create policy "Public read reviews" on reviews for select using (true);

drop policy if exists "Auth insert reviews" on reviews;
create policy "Auth insert reviews" on reviews for insert with check (auth.uid() is not null);

-- bookings: רק המשתמש עצמו קורא/כותב את ההזמנות שלו
drop policy if exists "Own bookings read" on bookings;
create policy "Own bookings read" on bookings for select using (auth.uid() = user_id);

drop policy if exists "Own bookings insert" on bookings;
create policy "Own bookings insert" on bookings for insert with check (auth.uid() = user_id);

-- 7. Seed products (lender_id=NULL for demo items, phone/email embedded directly)
insert into products (id, name, price, rating, reviews, category, location, description, image, lender_id, lender_name, lender_phone, lender_email, lender_response_time, lender_joined, lender_image)
values
(
  1, 'מקדחה מקצועית מקיטה', 40, 4.8, 12, 'כלי עבודה', '200 מ'' ממך',
  'מקדחה חזקה ואמינה, מתאימה לכל עבודות הבית. כולל סט מקדחים בסיסי. קלה לתפעול ונוחה לאחיזה.',
  'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800',
  NULL, 'ישראל ישראלי', '050-1111111', 'israel@sharehood.co.il', 'פחות משעה', 'מאי 2023', 'https://i.pravatar.cc/150?u=israel'
),
(
  2, 'אוהל 4 אנשים - פתיחה מהירה', 60, 4.9, 8, 'מחנאות', '500 מ'' ממך',
  'אוהל בן-רגע ל-4 אנשים, מושלם לקמפינג משפחתי. הקמה תוך 60 שניות. עמיד בגשם ורוח.',
  'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=800',
  NULL, 'מיכל כהן', '050-2222222', 'michal@sharehood.co.il', 'שעתיים', 'אוגוסט 2022', 'https://i.pravatar.cc/150?u=michal'
),
(
  3, 'מיקסר קיטשן אייד - אדום', 55, 4.7, 15, 'מטבח', '1.2 ק"מ ממך',
  'המיקסר הקלאסי והחזק של KitchenAid. מגיע עם וו לישה, מקצף ואביזר גיטרה. אידיאלי לאפייה מקצועית.',
  'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800',
  NULL, 'יוסי לוי', '050-3333333', 'yossi@sharehood.co.il', '30 דקות', 'ינואר 2024', 'https://i.pravatar.cc/150?u=yossi'
),
(
  4, 'מקרן קולנוע ביתי 4K', 80, 5.0, 5, 'אירוח', '800 מ'' ממך',
  'מקרן 4K איכותי לחוויית קולנוע ביתית מושלמת. הבהירות גבוהה וחיבור פשוט לכל מכשיר. כולל מסך הקרנה מתקפל.',
  'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&q=80&w=800',
  NULL, 'דנה אברהם', '050-4444444', 'dana@sharehood.co.il', 'שעה', 'מרץ 2023', 'https://i.pravatar.cc/150?u=dana'
),
(
  5, 'סט כלי עבודה חשמליים', 120, 4.6, 20, 'כלי עבודה', '1.5 ק"מ ממך',
  'סט מקיף הכולל מברגה, משחזת זווית ומסור אנכי. הכל מופעל על סוללות נטענות (כלולות).',
  'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=800',
  NULL, 'רוני גבאי', '050-5555555', 'roni@sharehood.co.il', '4 שעות', 'יוני 2021', 'https://i.pravatar.cc/150?u=roni'
),
(
  6, 'שק שינה לטמפרטורות קיצון', 30, 4.5, 3, 'מחנאות', '2.1 ק"מ ממך',
  'שק שינה איכותי המתאים לטמפרטורות של עד -5 מעלות. קל משקל ונוח לנשיאה.',
  'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?auto=format&fit=crop&q=80&w=800',
  NULL, 'עומר שטרן', '050-6666666', 'omer@sharehood.co.il', 'שעתיים', 'דצמבר 2023', 'https://i.pravatar.cc/150?u=omer'
),
(
  7, 'מכונת קפה אספרסו', 45, 4.9, 25, 'מטבח', '900 מ'' ממך',
  'מכונת אספרסו ביתית המפיקה קפה באיכות בית קפה. כולל מקציף חלב מובנה.',
  'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800',
  NULL, 'ליאת פז', '050-7777777', 'liat@sharehood.co.il', 'פחות משעה', 'פברואר 2022', 'https://i.pravatar.cc/150?u=liat'
),
(
  8, 'כיסאות מתקפלים לאירוח', 15, 4.3, 30, 'אירוח', '400 מ'' ממך',
  'סט של 10 כיסאות מתקפלים חזקים ונוחים. מושלם לאירועים בחצר או בבית.',
  'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&q=80&w=800',
  NULL, 'אביב משה', '050-8888888', 'aviv@sharehood.co.il', '5 שעות', 'אוקטובר 2023', 'https://i.pravatar.cc/150?u=aviv'
),
(
  9, 'אופני הרים מקצועיות', 70, 4.7, 7, 'ספורט', '3.2 ק"מ ממך',
  'אופני הרים 27.5 אינץ עם 21 הילוכים, מתלים קדמיים ובלמי דיסק. מתאים לשבילים ולכביש.',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
  NULL, 'עידן רייכל', '050-9999999', 'idan@sharehood.co.il', 'שעתיים', 'ספטמבר 2022', 'https://i.pravatar.cc/150?u=idan'
),
(
  10, 'מסור חשמלי לגינה', 50, 4.4, 4, 'גינה', '1.8 ק"מ ממך',
  'מסור חשמלי חזק לגיזום ענפים ועצים. מגיע עם שרשרת חדה ומוגן בטיחות. מתאים לשימוש ביתי.',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&q=80&w=800',
  NULL, 'גדי וילצ''רסקי', '050-1010101', 'gadi@sharehood.co.il', 'יום', 'יולי 2023', 'https://i.pravatar.cc/150?u=gadi'
),
(
  11, 'קונסולת PlayStation 5', 90, 4.9, 18, 'גיימינג', '600 מ'' ממך',
  'PS5 עם שני שלטים ו-3 משחקים. חווית גיימינג בלתי נשכחת לסופ"ש או לאירוע.',
  'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&q=80&w=800',
  NULL, 'תום ברק', '050-1212121', 'tom@sharehood.co.il', 'פחות משעה', 'נובמבר 2023', 'https://i.pravatar.cc/150?u=tom'
),
(
  12, 'עגלת תינוק מתקפלת', 25, 4.8, 11, 'תינוקות', '1.1 ק"מ ממך',
  'עגלת תינוק קלה ומתקפלת, מתאימה מגיל לידה עד 3 שנים. נקייה ובמצב מצוין.',
  'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800',
  NULL, 'נועה שפירא', '050-1313131', 'noa@sharehood.co.il', 'שעה', 'אפריל 2024', 'https://i.pravatar.cc/150?u=noa'
)
on conflict (id) do nothing;

-- 8. Seed reviews
insert into reviews (id, product_id, user_name, rating, date_text, comment)
values
(1,  1, 'רון לביא',    5, 'לפני שבועיים', 'מקדחה מצוינת, עשתה את העבודה בקלות. ישראל היה מאוד נחמד וגמיש בזמנים.'),
(2,  1, 'מיכל שרון',  4, 'לפני חודש',    'אחלה מכשיר, הגיע עם כל החלקים. היה קצת אבק אבל לא נורא.'),
(3,  2, 'דודו אהרון', 5, 'לפני 3 ימים',  'האוהל הכי נוח שהיה לי! נפתח באמת תוך דקה. נקי ומסודר.'),
(4,  2, 'יעל שלביה',  5, 'לפני שבועיים', 'שירות מעולה של מיכל. האוהל היה במצב חדש.'),
(5,  3, 'נועה קירל',  5, 'לפני שבוע',    'הכנתי איתו עוגות לכל המשפחה. עובד כמו סוס. יוסי מקסים!'),
(6,  4, 'סטטיק',      5, 'אתמול',         'וואו! איכות מטורפת. המקרן קטן וקומפקטי אבל התמונה ענקית וחדה.'),
(7,  4, 'בן אל',      5, 'לפני שבוע',    'סגר לנו פינה לערב סרט עם החברה. דנה הייתה סופר נחמדה.'),
(8,  5, 'עומר אדם',   4, 'לפני חודש',    'סט מעולה לשיפוץ. הסוללות מחזיקות המון זמן.'),
(9,  6, 'עדן בן זקן', 5, 'לפני שבועיים', 'היה לי חם ונעים כל הלילה בחרמון. מומלץ!'),
(10, 7, 'מרגי',       5, 'לפני 5 ימים',  'קפה מושלם. המכונה נקייה ופשוטה לשימוש.'),
(11, 8, 'אנה זק',     4, 'לפני שבוע',    'כיסאות נוחים, עשו את העבודה במסיבת יום הולדת.'),
(12, 9, 'טדי נגוסה',  5, 'לפני שבועיים', 'אופניים מטורפים, נהניתי מכל רגע במסלול.'),
(13, 10,'רביד פלוטניק',5,'לפני חודש',    'מסור חזק מאוד. גדי הסביר לי הכל בסבלנות.')
on conflict (id) do nothing;

-- 9. Reset sequences
select setval(pg_get_serial_sequence('products', 'id'), coalesce(max(id), 1)) from products;
select setval(pg_get_serial_sequence('reviews',  'id'), coalesce(max(id), 1)) from reviews;
select setval(pg_get_serial_sequence('bookings', 'id'), coalesce(max(id), 1)) from bookings;
